### PR TITLE
Update to the latest clp submodule commit.

### PR DESCRIPTION
**Pull request by LinZhihao-723**
# References

# Description

This PR updates to the latest version of CLP. This will include PR https://github.com/y-scope/clp/pull/341 to support Windows build.

# Validation performed

1. Tested locally to ensure the build flow worked and unit tests passed.
2. GitHub workflow all passed.

### CODE REVIEW

**Comment by junhaoliao** [comment]
Can we also pick the change from https://github.com/y-scope/clp/pull/341 after it is merged? 

(#56 needs that)

**Comment by LinZhihao-723** [comment]
> Can we also pick the change from [y-scope/clp#341](https://github.com/y-scope/clp/pull/341) after it is merged?
> 
> (#56 needs that)

Sure. I will update the submodule commit after CLP PR#341 merged.

**Comment by LinZhihao-723** [comment]
> Can we also pick the change from [y-scope/clp#341](https://github.com/y-scope/clp/pull/341) after it is merged?
> 
> (#56 needs that)

Done. Can u help review this PR?

**Review by junhaoliao — DISMISSED** [review]
Looks good to me. I'm less familiar with the C/C++ coding styles at YScope, so it would still be good to have someone else to take a look.

**Review by junhaoliao — DISMISSED** [review]

**Review by junhaoliao — APPROVED** [review]

**Pull request merged**
